apiVersion: v1
kind: Service
metadata:
  name: my-nginx1
  labels:
    app: nginx1
spec:
  type: NodePort
  ports:
  - port: 443
    name: https
  selector:
    app: nginx1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginx1secret
      - name: configmap-volume
        configMap:
          name: nginx1configmap
      containers:
      - name: nginx1https
        image: ymqytw/nginx1https:1.5
        command: ["/home/auto-reload-nginx1.sh"]
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx1/ssl
          name: secret-volume
        - mountPath: /etc/nginx1/conf.d
          name: configmap-volume
